<div class="row">
  <div class="add-form col-md-8 center-block">
    <h1>Vlozit aktualitu</h1>
    <form action="" method="post">
      <?php
      foreach ($aktualita as $value) {
          echo '<label for="">Nadpis:</label><br />';
          echo '<input class="form-control" type="text" name="nadpis" value="' . $value['nadpis'] . '" size="50" /><br /><br />';
          echo '<label for="">Obsah:</label><br />';
          echo '<textarea class="form-control" name="obsah" rows="8" cols="50">' . $value['obsah'] . '</textarea><br /><br />';
          echo '<label for="">Zveřejnit: </label> ';
          echo '<input type="checkbox" name="zobrazit" value="ano" '; if( $value['zobrazit'] == 'ano' ) {echo 'checked';} else {echo '';} echo ' /><br /><br />';
      }
      ?>
        
      <input class="btn btn-default" type="submit" name="ok" value="Ulozit" />
    </form>
  </div>
</div>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
        tinymce.init({
                        selector: "textarea[name=obsah]",
                        plugins: [
                                        //"advlist autolink lists link image charmap print preview anchor",
                                        //"searchreplace visualblocks code fullscreen",
                                        //"insertdatetime media table contextmenu paste"
                        ],
                        toolbar: "undo redo | bold italic | bullist numlist",
                        //toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                        entities: "160,nbsp",
                        entity_encoding: "named",
                        entity_encoding: "raw"
        });
</script>
