<style>
    table {
        width: 100%;
    }

    /*
    th, td {
        padding: 10px 10px;
    }

    th {
        text-align: left;
    }

    table tr:nth-child(even) {
        background-color: #eee;
    }

    table tr:nth-child(odd) {
        background-color: #fff;
    }

    table th {
        background-color: black;
        color: white;
    }
    */

    .datum {
        width: 110px;
        text-align: center;
    }

    .edit,
    .del {
        width: 80px;
        text-align: center;
    }
</style>

<div class="row">
    <div class="add-form col-md-11 center-block">
        <a href="/aktualita-add">Nová zpráva</a>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th class="datum">Datum:</th>
                <th>Nadpis:</th>
                <th class="edit">Upravit:</th>
                <th class="del">Smazat:</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $seznamAktualit = $this->data['seznamAktualit'];
            foreach ($seznamAktualit as $key => $value) {
                echo '<tr>';
                    echo '<td class="datum">' . $value['datum'] . '</td>';
                    echo '<td><strong>' . $value['nadpis'] . '</strong></td>';
                    echo '<td class="edit"><a href="/aktualita-edit?idaktualita=' . $value['idaktualita'] . '">upravit</a></td>';
                    echo '<td class="del"><a href="/aktualita-delete?idaktualita=' . $value['idaktualita'] . '">smazat</a></td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
