<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<style>
    table {
        width: 100%;
    }

    .datum {
        width: 110px;
        text-align: center;
    }

    .poradi {
        /*width: 30px;*/
        text-align: center;
    }

    .material-symbols-outlined {
        color: silver;
    }

    .edit,
    .del {
        width: 80px;
        text-align: center;
    }
</style>

<div class="row">
    <div class="add-form col-md-11 center-block">
        <a href="/aktualita-add" class="btn btn-primary">Nová zpráva</a> <br/><br/>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th class="datum">Datum:</th>
                <th class="poradi">Pořadí:</th>
                <th>Nadpis:</th>
                <th class="edit">Upravit:</th>
                <th class="del">Smazat:</th>
            </tr>
            </thead>
            <tbody id="sortable">
            <?php
            $seznamAktualit = $this->data['seznamAktualit'];
            foreach ($seznamAktualit as $key => $value) {
                echo '<tr data-id="' . $value['idaktualita'] . '">';
                echo '<td class="datum">' . $value['datum'] . '</td>';
                echo '<td class="poradi"><a href="#"><span class="material-symbols-outlined">drag_handle</span></a> </td>';
                echo '<td><strong><a href="/aktualita?idaktualita=' . $value['idaktualita'] . '">' . $value['nadpis'] . '</a></strong></td>';
                echo '<td class="edit"><a href="/aktualita-edit?idaktualita=' . $value['idaktualita'] . '">upravit</a></td>';
                echo '<td class="del"><a href="/aktualita-delete?idaktualita=' . $value['idaktualita'] . '">smazat</a></td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
</div>

<script>
    $("#sortable").sortable({
        update: function (event, ui) {
            var order = $(this).sortable("toArray", {
                attribute: 'data-id'
            });
            // Odeslání nového pořadí na server
            $.post('/admin', {order: order});
        }
    });
</script>