<div class="row">
    <div class="add-form col-md-11 center-block">
        <a href="/home">Zpět</a>
        <?php $aktualita = $this->data['aktualita']; ?>
        <h1><?php echo $aktualita['nadpis']; ?></h1>
        <div class="perex"><?php echo $aktualita['perex']; ?></div>
        <div class="perex"><?php echo $aktualita['perex']; ?></div>
        <div class="obsah"><?php echo $aktualita['obsah']; ?></div>
    </div>
</div>
