  <div class="gallery-block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <!--<h1>Naše ordinace</h1>-->
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/1.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/1.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/2.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/2.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/3.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/3.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/4.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/4.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/5.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/5.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/6.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/6.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/7.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/7.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/8.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/8.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/9.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/9.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/10.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/10.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/11.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/11.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/12.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/12.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/13.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/13.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/14.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/14.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/15.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/15.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/16.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/16.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/17.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/17.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/18.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/18.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/19.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/19.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/20.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/20.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
      <div class="row images-row">
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/21.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/21.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/22.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/22.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/23.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/23.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-3">
          <a href="../images/gallery/24.jpg" data-lightbox="image-1" data-title=""><img src="../images/gallery/male/24.jpg" alt="" class="img-responsive" data-lightbox="roadtrip" /></a>
        </div>
      </div>
    </div>
  </div>
