<div class="col-md-8">

<h1>INFORMACE PRO PACIENTY O ZPRACOVÁNÍ OSOBNÍCH ÚDAJŮ</h1>

<p>podle nařízení Evropského parlamentu a Rady (EU) 2016/679 ze dne 27. dubna 2016 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů a o zrušení směrnice 95/46/ES (obecné nařízení o ochraně osobních údajů)</p>

<h2>I. Správce osobních údajů</h2>

<p>Medipraktik Zlín s.r.o., IČO 27754189, 760 01 Zlín Kotěrova 5529, <a href="https://www.iordinace.cz">www.iordinace.cz</a></p>

<p>Správce je poskytovatelem zdravotních služeb v souladu se zákonem č. 372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování, ve znění pozdějších předpisů.</p>

<h2>II. Účel/y zpracování osobních údajů</h2>

<p>Vaše osobní údaje zpracováváme za účelem:</p>

<ul>
    <li>poskytování zdravotních služeb</li>
    <li>vykazování hrazených zdravotních služeb</li>
    <li>vyúčtování nehrazených zdravotních služeb</li>
    <li>sdělování údajů o zdravotním stavu Vám a dalším oprávněným osobám</li>
    <li>organizace poskytování zdravotních služeb (objednávání pacientů)</li>
    <li>vedení evidence o našich příjmech a výdajích, přijatých platbách a o hospodaření, jak vyplývají z předpisů upravujících daně a účetnictví</li>
</ul>

<h2>III. Právní základ zpracování osobních údajů</h2>

<p>Právním základem pro zpracování Vašich osobních údajů uvedených v bodu II. je:</p>

<ul>
    <li>splnění naší zákonné povinnosti (zejména zákon č. 372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování, zákon č. 48/1997 Sb., o veřejném zdravotním pojištění, zákon č. 563/1991 Sb., o účetnictví, zákon č. 586/1992 Sb., o daních z příjmů, zákon č. 634/1992, o ochraně spotřebitele)</li>
    <li>splnění závazků ze smlouvy o péči o zdraví, na jejímž základě Vám poskytujeme zdravotní služby (tato smlouva nemusí být uzavřena písemně)</li>
</ul>

<h2>IV. Příjemci osobních údajů</h2>

<p>Příjemci Vašich osobních údajů mohou v souladu s ustanoveními právních předpisů v konkrétních případech kromě Vás být: poskytovatel zdravotních služeb, orgány veřejné moci a osoby oprávněné nahlížet do zdravotnické dokumentace podle § 31, § 32, § 33 a § 65 zákona č. 372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování. Osobní údaje mohou být pro zajištění výše popsaných účelů zpracovávány vedle správce také zpracovateli, a to na základě smluv o zpracování osobních údajů uzavřených v souladu s obecným nařízením o ochraně osobních údajů. Vaše osobní údaje nepředáváme do zahraničí.</p>

<h2>V. Doba zpracování osobních údajů</h2>

<p>Osobní údaje obsažené ve zdravotnické dokumentaci jsou zpracovávány po dobu stanovenou vyhláškou č. 98/2012 Sb., o zdravotnické dokumentaci. Osobní údaje zpracovávané pro další účely uvedené v bodu III jsou zpracovávány po dobu stanovenou zákonem nebo po dobu, po kterou budete naším pacientem, a následně po dobu jednoho roku poté, co naším pacientem přestanete být.</p>

<h2>VI. Práva subjektu údajů</h2>

<p>Při zpracování osobních údajů máte následující práva týkající se ochrany svých osobních údajů:</p>

<ul>
    <li>právo požadovat od nás přístup k Vašim osobním údajům;</li>
    <li>právo na opravu Vašich osobních údajů, které zpracováváme;</li>
    <li>právo na omezení zpracování. Omezení zpracování znamená, že musíme Vaše osobní údaje, u nichž bylo zpracování omezeno, označit a po dobu trvání omezení je nesmíme dál zpracovávat s výjimkou jejich uložení. </li>
</ul>

<p>Právo na omezení zpracování máte tehdy, jestliže:</p>

<ul>
    <li>popíráte přesnost osobních údajů, a to na dobu potřebnou k tomu, abychom mohli přesnost osobních údajů ověřit;</li>
    <li>zpracování je protiprávní a Vy odmítáte výmaz osobních údajů a žádáte místo toho o omezení jejich použití;</li>
    <li>jestliže již Vaše osobní údaje nepotřebujeme pro účely zpracování, ale Vy je požadujete pro určení, výkon nebo obhajobu právních nároků;</li>
    <li>jestliže jste vznesl/a námitku proti zpracování uvedenou níže v bodu VII., dokud nebude ověřeno, zda naše oprávněné důvody pro zpracování převažují nad Vašimi zájmy nebo právy a svobodami;</li>
    <li>právo na výmaz osobních údajů. Právo na výmaz osobních údajů se vztahuje jen na osobní údaje, které zpracováváme k jiným účelům, než je poskytování zdravotních služeb. Údaje, které o Vás vedeme za účelem poskytování zdravotních služeb (např. ve zdravotnické dokumentaci), vymazat nesmíme;</li>
    <li>právo na přenositelnost údajů. Můžete žádat, abychom Vám Vaše osobní údaje poskytli za účelem jejich předání jinému správci osobních údajů, nebo abychom je sami předali jinému správci osobních údajů. Toto právo však máte pouze ohledně těch údajů, které zpracováváme automatizovaně na základě Vašeho souhlasu nebo smlouvy s Vámi. Údaje, které o Vás vedeme za účelem poskytování zdravotních služeb (např. ve zdravotnické dokumentaci), však smíme poskytnout jen Vám a za zákonných podmínek též jinému poskytovateli zdravotních služeb nebo orgánu veřejné moci.</li>
    <li>právo podat stížnost u dozorového úřadu, a to v případě, že se domníváte, že zpracováním osobních údajů dochází k porušení právních předpisů o ochraně osobních údajů. Stížnost můžete podat u dozorového úřadu v místě svého obvyklého bydliště, místě výkonu zaměstnání nebo v místě, kde došlo k údajnému porušení. V České republice je dozorovým úřadem Úřad na ochranu osobních údajů, Pplk. Sochora 27, 170 00 Praha 7, <a href="https://www.uoou.cz">www.uoou.cz.</a></li>
</ul>

<h2>VII. Právo vznést námitku proti zpracování</h2>

<p>V případě, že Vaše osobní údaje zpracováváme pro účely oprávněných zájmů našich nebo někoho dalšího (právní základy zpracování jsou uvedeny v bodu III), máte kdykoliv právo vznést proti takovému zpracování námitku. Námitku můžete vznést na naší adrese uvedené v bodu I. Pokud takovou námitku vznesete, budeme oprávněni v takovém zpracování pokračovat jen tehdy, pokud prokážeme závažné oprávněné důvody pro zpracování, které převažují nad Vašimi zájmy nebo právy a svobodami, a dále tehdy, pokud půjde o zpracování nezbytné pro určení, výkon nebo obhajobu právních nároků.</p>

<h2>VIII.  Povinné zpracování a povinnost poskytnout osobní údaje</h2>



<p>Zpracování Vašich osobních údajů pro účely poskytování zdravotních služeb je zákonným požadavkem. Neposkytnutím Vašich osobních údajů může znamenat, že Vám nebudeme moci poskytnout zdravotní služby, čímž může dojít k poškození Vašeho zdraví či přímému ohrožení života (§ 41 odst.1 písm. d) zákona č. 372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování). Povinnost poskytnout osobní údaje pacienta se týká i jeho zákonného zástupce nebo opatrovníka (§ 41 odst. 2 zákona č. 372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování).</p>

<p><strong>MUDr. Martina Přecechtělová, Medipraktik Zlín s.r.o.</strong></p>
<p>Zapsána v obchodním rejstříku vedeném KS v Brně, odd. C, vložka 56708</br>
<strong>se sídlem:</strong> Kotěrova 5529, Zlín, PSČ: 760 01,</br>
<strong>IČ:</strong> 27754189, <strong>tel.:</strong> +420.732.941.611, <strong>email:</strong> <a href="mailto:precechtelova@iordinace.cz">precechtelova@iordinace.cz</a></p>

</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-3.jpg" alt="" class="illustrace img-responsive" />
</div>



