<style>
    .mudr {
        width: 350px;
        background-color: #efefef;
        padding: 0px 0 15px 30px;
        margin-bottom: 20px;
    }

    @media (max-width: 370px) {
        .mudr {
            padding: 15px;
            width: 250px;
        }
    }

    .dovolena-text {
        max-width: 750px;
        margin: 0 auto 50px auto;
        font-weight: bold;
    }

    @media (max-width: 1050px) {
        .dovolena-text {
            width: 85%;
        }
    }

    table {
        width: 100%;
    }

    .aktuality {
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    .aktualita {
        flex: 1 1 20%;
        margin: 25px;
    }

    .aktualita-perex {
        margin-top: 20px;
        margin-bottom: 30px;
        /*border-left: 25px solid #e872c0;*/
        /*padding: 0 0 0 20px;*/
        line-height: 150%;
        font-size: 18px;
    }

    .aktualita-detail a {
        text-align: left;
        font-size: 18px;
        text-decoration: underline;
    }
</style>
<div class="home-page">

    <div class="aktuality">
        <?php
            $aktuality = $this->data['aktuality'];
            foreach ($aktuality as $aktualita) {
        ?>
            <article class="aktualita">
                <h2><a href="/aktualita?idaktualita=<?php echo $aktualita['idaktualita'] ?>"><?php echo $aktualita['nadpis'] ?></a></h2>
                <div class="aktualita-perex"><?php echo HelperKontroler::zkratitText($aktualita['perex']); ?></div>
                <p class="aktualita-detail"><a href="/aktualita?<?php echo $aktualita['idaktualita'] ?>">Detail</a></p>
            </article>
        <?php }; ?>
    </div>

    <div class="persons row">
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-bacova.jpg" alt="" class="img-responsive"/>
            <h3>MUDr. Miluše Bačová</h3>
            <p>Narozena 1943, atestace z dětského lékařství 1971, bohatá praxe jak v nemocniční tak ambulantní
                sféře.</p>
        </div>
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-precechtelova.jpg" alt="" class="img-responsive"/>
            <h3>MUDr. Martina Přecechtělová</h3>
            <p>Narozena 1972, atestace z dětského lékařství 1999.</p>
        </div>
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-hola.jpg" alt="" class="img-responsive"/>
            <h3>Renata Holá</h3>
            <p>Narozena 1975, akreditovaná dětská sestra.</p>
        </div>
    </div>

    <div class="home-introduction row">
        <div class="introduction-list col-sm-6 col-md-6">
            <div class="item-text">
                <div class="number">1.</div>
                <p>Děti mladší 15 let musí být v doprovodu alespoň jednoho zákonného zástupce, který svůj souhlas s
                    vyšetřením a následnou péčí písemně zaznamená do zdravotnické dokumentace.</p>
            </div>
            <div class="item-text">
                <div class="number">2.</div>
                <p>Pokud se bude jednat o poskytnutí zdravotní péče, která může podstatným způsobem ovlivnit zdraví
                    pacienta, je třeba písemného souhlasu obou rodičů.</p>
            </div>
            <div class="item-text">
                <div class="number">3.</div>
                <p>Prarodiče nemají postavení zákonného zástupce, tedy nemohou rozhodovat o udělení souhlasu či
                    nesouhlasu se zdravotní péčí. V úvahu přichází udělit ze strany rodiče plnou moc prarodiči a ten
                    potom uděluje souhlas k výkonům namísto rodiče.</p>
            </div>
        </div>

        <div class="standards col-sm-6 col-md-6">
            <div class="item-text">
                <div class="number">4.</div>
                <p>Děti starší 15 let musí mít od rodičů udělen písemný souhlas k tomu, aby jim mohla být poskytována
                    zdravotní péče bez doprovodu zákonného zástupce. Informovaný souhlas uděluje dítě samo.</p>
            </div>
            <div class="item-text">
                <div class="number">5.</div>
                <p>U veškerého nepovinného očkování je třeba písemného souhlasu obou rodičů eventuelně i nezletilého nad
                    14 let v písemné formě.</p>
            </div>
            <!--<ul class="home-standardy">
              <li><a href="preventivni-prohlidky">Preventivní prohlídky</a></li>
              <li><a href="pro-budouci-maminky">Pro budoucí maminky</a></li>
              <li><a href="ockovani">Očkování</a></li>
              <li><a href="nadstandardni-sluzby">Nadstandardní služby</a></li>
            </ul>-->
        </div>
    </div>
</div>
