<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
<style>
    .mudr {
        width: 350px;
        background-color: #efefef;
        padding: 0px 0 15px 30px;
        margin-bottom: 20px;
    }

    @media (max-width: 370px) {
        .mudr {
            padding: 15px;
            width: 250px;
        }
    }

    .dovolena-text {
        max-width: 750px;
        margin: 0 auto 50px auto;
        font-weight: bold;
    }

    @media (max-width: 1050px) {
        .dovolena-text {
            width: 85%;
        }
    }

    table {
        width: 100%;
    }

    .aktuality {
        display: flex;
        justify-content: flex-start;
        flex-wrap: wrap;
        margin-bottom: 100px;
    }

    .aktualita {
        flex: 0 1 calc(100% / 4);
        padding: 0 20px 40px 20px;
        margin: 0;
    }

    .aktualita h2 {
        margin-top: 0;
        line-height: 140%;
        font-size: 22px;
    }

    .aktualita h2 .material-symbols-outlined {
        margin-right: 10px;
        color: #e872c0;
        display: inline-block;
        position: relative;
        top: 5px;
    }

    .aktualita-perex {
        margin-top: 20px;
        margin-bottom: 30px;
        line-height: 150%;
        font-size: 16px;
    }

    .aktualita-detail .material-symbols-outlined {
        margin-right: 5px;
        color: #e872c0;
        display: inline-block;
        position: relative;
        top: 6px;
    }

    .aktualita-detail a {
        text-align: left;
        font-size: 18px;
        text-decoration: underline;
    }

    @media screen and (max-width: 1200px) {
        .aktuality {
            justify-content: space-between;
        }

        .aktualita {
            flex: 0 1 calc(100% / 3);
            padding: 0 20px 40px 20px;
        }

        .aktualita h2 {
            font-size: 20px;
        }

        .aktualita .datum {
            font-size: 16px;
        }

        .aktualita .perex {
            font-size: 16px;
        }
    }

    @media screen and (max-width: 850px) {
        .aktualita {
            flex: 0 1 calc(100% / 2);
            padding: 0 20px 40px 20px;
        }
    }

    @media screen and (max-width: 550px) {
        .aktualita {
            flex: 0 1 calc(100%);
            padding: 0 20px 20px 20px;
        }
    }
</style>
<div class="home-page">

    <div class="aktuality">
        <?php
        $aktuality = $this->data['aktuality'];
        foreach ($aktuality as $aktualita) {
            ?>
            <article class="aktualita">

                <h2><span class="material-symbols-outlined">mark_unread_chat_alt</span><a href="/aktualita?idaktualita=<?php echo $aktualita['idaktualita'] ?>"><?php echo $aktualita['nadpis'] ?></a></h2>
                <strong class="perex"><?php echo $aktualita['datum']; ?></strong>
                <div class="aktualita-perex"><?php echo HelperKontroler::zkratitText($aktualita['perex']); ?></div>
                <?php if (strlen($aktualita['perex']) >= 350) { ?>
                    <p class="aktualita-detail">
                        <span class="material-symbols-outlined">read_more</span>
                        <a href="/aktualita?<?php echo $aktualita['idaktualita'] ?>">Více</a>
                    </p>
                <?php }; ?>
            </article>
        <?php }; ?>
    </div>

    <div class="persons row">
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-bacova.jpg" alt="" class="img-responsive"/>
            <h3>MUDr. Miluše Bačová</h3>
            <p>Narozena 1943, atestace z dětského lékařství 1971, bohatá praxe jak v nemocniční tak ambulantní
                sféře.</p>
        </div>
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-precechtelova.jpg" alt="" class="img-responsive"/>
            <h3>MUDr. Martina Přecechtělová</h3>
            <p>Narozena 1972, atestace z dětského lékařství 1999.</p>
        </div>
        <div class="osoba col-sm-4 col-md-4">
            <img src="../images/home-hola.jpg" alt="" class="img-responsive"/>
            <h3>Renata Holá</h3>
            <p>Narozena 1975, akreditovaná dětská sestra.</p>
        </div>
    </div>

    <div class="home-introduction row">
        <div class="introduction-list col-sm-6 col-md-6">
            <div class="item-text">
                <div class="number">1.</div>
                <p>Děti mladší 15 let musí být v doprovodu alespoň jednoho zákonného zástupce, který svůj souhlas s
                    vyšetřením a následnou péčí písemně zaznamená do zdravotnické dokumentace.</p>
            </div>
            <div class="item-text">
                <div class="number">2.</div>
                <p>Pokud se bude jednat o poskytnutí zdravotní péče, která může podstatným způsobem ovlivnit zdraví
                    pacienta, je třeba písemného souhlasu obou rodičů.</p>
            </div>
            <div class="item-text">
                <div class="number">3.</div>
                <p>Prarodiče nemají postavení zákonného zástupce, tedy nemohou rozhodovat o udělení souhlasu či
                    nesouhlasu se zdravotní péčí. V úvahu přichází udělit ze strany rodiče plnou moc prarodiči a ten
                    potom uděluje souhlas k výkonům namísto rodiče.</p>
            </div>
        </div>

        <div class="standards col-sm-6 col-md-6">
            <div class="item-text">
                <div class="number">4.</div>
                <p>Děti starší 15 let musí mít od rodičů udělen písemný souhlas k tomu, aby jim mohla být poskytována
                    zdravotní péče bez doprovodu zákonného zástupce. Informovaný souhlas uděluje dítě samo.</p>
            </div>
            <div class="item-text">
                <div class="number">5.</div>
                <p>U veškerého nepovinného očkování je třeba písemného souhlasu obou rodičů eventuelně i nezletilého nad
                    14 let v písemné formě.</p>
            </div>
            <!--<ul class="home-standardy">
              <li><a href="preventivni-prohlidky">Preventivní prohlídky</a></li>
              <li><a href="pro-budouci-maminky">Pro budoucí maminky</a></li>
              <li><a href="ockovani">Očkování</a></li>
              <li><a href="nadstandardni-sluzby">Nadstandardní služby</a></li>
            </ul>-->
        </div>
    </div>
</div>
