<div class="home-page">


<?php

while ($uzivatel = $zobrazit->fetch_assoc()) {
  $publikovat = $uzivatel['zobrazit'];
}

if($publikovat == 'ano') {
if(!empty($aktualita)) {
  //echo '<div class="row">';
    echo '<div class="home-aktualita col-md-12">';
      echo '<div class="home-aktualita-in">';

        echo '<h2>Důležité informace související s GDPR:</h2>';
        echo '<ul>';
        echo '<li>Telefonické informace ohledně zdravotního stavu dítěte a výsledků vyšetření  jsou sdělovány pouze rodičům - zákonným zástupcům dítěte - po identifikaci heslem, které bude osobně sděleno v ordinaci.</li>';	
        echo '<li>Zasílání lékařských zpráv nebo výsledků vyšetření  je možné jen zabezpečenou komunikací přes naše internetové stránky. Bližší informace podáme v ordinaci.</li>';
        echo '</ul>';

        foreach ($aktualita as $value) {
          echo '<h2>' . $value['nadpis'] . '</h2>';
          echo '<p>' . $value['obsah'] . '</p>';
        }
    if(isset($_SESSION['logged_user'])) {
        echo '<p><a href="addaktualita">Upravit</a>';
    }
      echo '</div>';
    echo '</div>';
  //echo '</div>';
} else {
    echo '';
}

}



?>

  <div class="persons row">
    <div class="osoba col-sm-4 col-md-4">
      <img src="../images/home-bacova.jpg" alt="" class="img-responsive" />
      <h3>MUDr. Miluše Bačová</h3>
      <p>Narozena 1943, atestace z dětského lékařství 1971, bohatá praxe jak v nemocniční tak ambulantní sféře.</p>
    </div>
    <div class="osoba col-sm-4 col-md-4">
      <img src="../images/home-precechtelova.jpg" alt="" class="img-responsive" />
      <h3>MUDr. Martina Přecechtělová</h3>
      <p>Narozena 1972, atestace z dětského lékařství 1999.</p>
    </div>
    <div class="osoba col-sm-4 col-md-4">
      <img src="../images/home-hola.jpg" alt="" class="img-responsive" />
      <h3>Renata Holá</h3>
      <p>Narozena 1975, akreditovaná dětská sestra.</p>
    </div>
  </div>

  <div class="home-introduction row">

      <div class="introduction-list col-sm-6 col-md-6">
        <div class="item-text">
          <div class="number">1.</div>
          <p>Děti mladší 15 let musí být v doprovodu alespoň jednoho zákonného zástupce, který svůj souhlas s vyšetřením a následnou péčí písemně zaznamená do zdravotnické dokumentace.</p>
        </div>
        <div class="item-text">
          <div class="number">2.</div>
          <p>Pokud se bude jednat o poskytnutí zdravotní péče, která může podstatným způsobem ovlivnit zdraví pacienta, je třeba písemného souhlasu obou rodičů.</p>
        </div>
        <div class="item-text">
          <div class="number">3.</div>
          <p>Prarodiče nemají postavení zákonného zástupce, tedy nemohou rozhodovat o udělení souhlasu či nesouhlasu se zdravotní péčí. V úvahu přichází udělit ze strany rodiče plnou moc prarodiči a ten potom uděluje souhlas k výkonům namísto rodiče.</p>
        </div>
      </div>

      <div class="standards col-sm-6 col-md-6">
        <div class="item-text">
          <div class="number">4.</div>
          <p>Děti starší 15 let musí mít od rodičů udělen písemný souhlas k tomu, aby jim mohla být poskytována zdravotní péče bez doprovodu zákonného zástupce. Informovaný souhlas uděluje dítě samo.</p>
        </div>
        <div class="item-text">
          <div class="number">5.</div>
          <p>U veškerého nepovinného očkování je třeba písemného souhlasu obou rodičů eventuelně i nezletilého nad 14 let v písemné formě.</p>
        </div>
        <!--<ul class="home-standardy">
          <li><a href="preventivni-prohlidky">Preventivní prohlídky</a></li>
          <li><a href="pro-budouci-maminky">Pro budoucí maminky</a></li>
          <li><a href="ockovani">Očkování</a></li>
          <li><a href="nadstandardni-sluzby">Nadstandardní služby</a></li>
        </ul>-->
      </div>

  </div>

</div>
