<?php
$username = (isset($_POST['username'])) ? $_POST['username'] : '';
$heslo = (isset($_POST['heslo'])) ? $_POST['heslo'] : '';
?>
<div class="login-form col-md-3 center-block">
    <form action="" method="post">
        <div class="form-group">
            <label for="username">Uživatelské jméno:</label><br/>
            <input class="form-control" type="text" name="username" value=""/><br/>
        </div>
        <div class="form-group">
            <label for="heslo">Heslo:</label><br/>
            <input class="form-control" type="password" name="heslo" value=""/><br/>
        </div>
        <input class="btn btn-default" type="submit" name="prihlasit" value="Prihlasit"/>
    </form>
</div>
