<div class="col-md-8">
  <h1>Nadstandardní služby</h1>
  <p>V ordinaci máme přístroj na měření CRP. Jedná se o vyšetření, které z kapky krve odebrané z prstu dokáže určit stupeň závažnosti zánětlivého onemocnění a umožní odlišit virovou a bakteriální infekci. Toto rozlišení v řadě případů může ušetřit dítě zbytečného podání antibiotik (antibiotika neovlivní infekci způsobenou viry, pouze bakteriemi). Celé vyšetření trvá 3-4 minuty.</p>

  <p>Rodiče mají k dispozici bezplatný kontakt přes mobilní telefon a to i o sobotách a nedělích. Slouží ke konzultaci při náhlém zhoršení stavu dítěte, poradám při aktuálních problémech především u malých dětí atp.</p>

  <p>Provádíme odběry krve (dle potřeby též v laboratoři), výtěry na mikrobiologické vyšetření.</p>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-4.jpg" alt="" class="illustrace img-responsive" />
</div>
