<div class="col-md-8">
  <h1>Očkování</h1>

  <p>Od 1.11.2010 bylo zrušeno celoplošné povinné očkování proti TBC, lze zahájit pravidelné očkování hexavakcínou již od 9. týdne věku, samozřejmě po posouzení zdravotního stavu dítěte ošetřujícím dětským lékařem. Tato očkovací látka vytváří obranné látky proti tetanu, záškrtu, černému kašli, dětské obrně, hepatitidě typu B a hemofilovým infekcím.</p>

  <h2>Nový očkovací kalendář vypadá následovně:</h2>

  <ul>
    <li>Od 9.týdne věku dostává 3 dávky hexavakcíny v intervalu 1 měsíce. Čtvrtá dávka by měla být aplikována do 18. měsíce věku dítěte.</li>
    <li>Po 15. měsíci věku následuje první očkování proti spalničkám, zarděnkám a příušnicím, druhá dávka pak za 6 - 12 měsíců po první. Alternativou tohoto očkování je vakcína Priorix-tetra, u níž je přidáno ještě očkování proti planým neštovicím</li>
    <li>V 5 letech očkování proti záškrtu, tetanu a černému kašli.</li>
    <li>Mezi 10.-11.rokem očkování proti záškrtu, tetanu, černému kašli a dětské obrně.</li>
    <li>Ve 12 letech očkování proti hepatitidě B u dětí, které ještě nebyly proti žloutence očkovány. Očkování sestává ze 3 dávek 0-1-6 měsíců po sobě.</li>
  </ul>

  <h2>Nepovinná očkování</h2>

  <p><strong>Očkování proti pneumokokům</strong> - plně hrazeno z veřejného zdravotního pojištění, je-li očkování zahájeno mezi třetím a pátým měsícem věku dítěte a pokud jsou 3 dávky vakcíny aplikovány do sedmého měsíce věku.</p>

  <p><strong>Klíšťová encefalitida</strong> - základní jsou 3 dávky, přeočkování za 3-5 let. Orientační cena 400,-</p>

  <p><strong>Hepatitida A</strong> - sestává ze dvou dávek v odstupu 6 měsíců. Orientační cena 700,-</p>
  <p><strong>Kombinovaná látka proti hepatitidě A+B</strong> - - pro děti, které dosud žádné očkování proti žloutence nemají. Tři dávky v intervalu 0-1-6 měsíců. Orientační cena 1000,-</p>
  <p><strong>Meningokok typu C</strong> - aplikuje se jedna dávka. Orientační cena 650,-</p>
  <p><strong>Chřipka</strong> - očkuje se u dětí od 6 měsíců věku. Je nutné každoročně přeočkovat. Vhodná doba na očkování září, říjen. Orientační cena 150,-</p>
  <p><strong>Plané neštovice</strong> - očkuje se dvěma dávkami v odstupu 6 týdnů až 3 měsíce. Podrobné informace na www.nestovice.cz. Orientační cena 1400,-</p>
  <p><strong>Očkování proti rakovině děložního čípku</strong> - nejvhodnější je očkovat dívky ve věku 13 - 15 let, lze i později. Očkování sestává ze 3 dávek (0 - 1 - 5 měsíců), je účinné a bezpečné. Na toto očkování přispívají zdravotní pojišťovny. Orientační cena 3000,-</p>
  <p><strong>Očkování proti rotavirům</strong> - u dětí do 6 měsíců věku, dle typu vakcíny 2 nebo 3 dávky. Orientační cena 1500,-</p>
  <p>Bližší informace k jednotlivým vakcínám na www.vakciny.net</p>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-3.jpg" alt="" class="illustrace img-responsive" />
</div>
