<div class="col-md-8">
  <h1>Odkazy</h1>

  <ul>
    <li><a href="http://www.kojeni.cz">www.kojeni.cz</a></li>
    <li><a href="http://www.ockovanideti.cz">www.ockovanideti.cz</a></li>
    <li><a href="http://www.porodnice.cz">www.porodnice.cz</a></li>
    <li><a href="http://www.detskyrust.cz">www.detskyrust.cz</a></li>
    <li><a href="http://www.miminko.com">www.miminko.com</a></li>
    <li><a href="http://www.rodina.cz">www.rodina.cz</a></li>
    <li><a href="http://www.vyzivadeti.cz">www.vyzivadeti.cz</a></li>
    <li><a href="http://www.rodice-a-deti.cz">www.rodice-a-deti.cz</a></li>
  </ul>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-6.jpg" alt="" class="illustrace img-responsive" />
</div>
