<div class="col-md-8">
  <h1>Preventivní prohlídky</h1>
  <p>Preventivní prohlídky jsou plně hrazeny ze zdravotního pojištění.</p>

  <p>Náplní preventivních prohlídek je zhodnocení tělesného, psychomotorického a sociálního vývoje dítěte, dále průběžná kontrola očkování, zhodnocení eventuálních omezení při výběru povolání apod.</p>

  <p>Porucha vývoje, dynamiky růstu a prospívání může jako první upozornit na probíhající chronické onemocnění či psychosociální problém dítěte nebo dospívajícího.</p>

  <p><strong>Systém preventivních prohlídek hrazených ze zdravotního pojištění:</strong></p>

  <ul>
    <li>První prohlídka novorozence</li>
    <li>Prohlídka v 6 týdnech věku</li>
    <li>Prohlídka ve 3 měsících věku</li>
    <li>Prohlídka ve 4 měsících věku</li>
    <li>Prohlídka v 5 měsících věku</li>
    <li>Prohlídka v 6 měsících věku</li>
    <li>Prohlídka v 8 měsících věku</li>
    <li>Prohlídka v 10 měsících věku</li>
    <li>Prohlídka ve 12 měsících věku</li>
    <li>Prohlídka v 18 měsících věku</li>
    <li>Prohlídka ve 3 letech</li>
    <li>Prohlídka v 5 letech</li>
    <li>Prohlídka v 7 letech</li>
    <li>Prohlídka v 9 letech</li>
    <li>Prohlídka v 11 letech</li>
    <li>Prohlídka v 13 letech</li>
    <li>Prohlídka v 15 letech</li>
    <li>Prohlídka v 17 letech</li>
    <li>Výstupní prohlídka v 19 letech, předání dospívajícího praktickému lékaři pro dospělé</li>
  </ul>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-1.jpg" alt="" class="illustrace img-responsive" />
</div>
