<div class="col-md-8">
  <h1>Pro budoucí maminky</h1>

  <p>Nastávajícím maminkám umožňujeme navštívit naši ordinaci ještě před porodem a seznámit se s prostředím poradny, kam budou s miminkem docházet.</p>

  <p>První vyšetření novorozence je prováděno lékařem a dětskou sestrou v domácím prostředí.</p>

  <p>Rádi poradíme, jak se připravit na příchod z porodnice, co si doma pro miminko přichystat a zodpovíme všechny další otázky.</p>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-2.jpg" alt="" class="illustrace img-responsive" />
</div>
