<div class="col-md-8">
  <h1>Smluvní pojišťovny</h1>

  <p>Smlouvy máme uzavřeny s následujícími zdravotními pojišťovnami:</p>

  <ul>
    <li>Všeobecná zdravotní pojišťovna (VZP) 111</li>
    <li>Vojenská zdravotní pojišťovna (VoZP) 201</li>
    <li>Česká průmyslová zdravotní pojišťovna (ČPZP) 205</li>
    <li>Oborová zdravotní pojišťovna (OZP) 207</li>
    <li>Zdravotní pojišťovna Ministerstva vnitra (ZP MV) 211</li>
    <li>Pojišťovna VZP, a.s. - smluvní pojištění pro cizince 333</li>
    <li>Revírní bratrská pokladna (RBP) 213</li>
    <li>Zdravotní pojišťovna Metal - Aliance (ZPM-A) 217</li>
    <li>Zdravotní pojišťovna Média 228</li>
  </ul>
</div>
<div class="col-md-4">
  <img src="../images/sidebox/sidebox-5.jpg" alt="" class="illustrace img-responsive" />
</div>
